apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: kube-prometheus-stack
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 77.*.*
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/values/values.yaml
    - repoURL: git@github.com:davidcardoso-homelab/monitoring.git
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: prometheus-kube-prometheus-admission
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: prometheus-kube-prometheus-admission