apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana  
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/hdd/k3s/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/prometheus

