apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  description: Projeto do kube-prometheus-stack gerenciado pelo ArgoCD
  sourceRepos:
    - 'git@github.com:davidcardoso-homelab/monitoring.git'
    - 'https://prometheus-community.github.io/helm-charts'
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
